services:
  redis:
    image: redis/redis-stack-server:7.2.0-v6
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data
  php:
    build: .
    ports:
      - "80:80" # HTTP
    volumes:
      - ./:/app
    tty: true
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      XDEBUG_MODE: 'coverage'

volumes:
  redis_data: